# Module: system
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.3/metricbeat-module-system.html

- module: system
  period: 5m
  metricsets:
#    - cpu
#    - load
#    - memory
#    - network
#    - process
#    - process_summary
#    - uptime
#    - socket_summary
#    #- entropy
#    - core
#    - diskio
    - filesystem
#    - fsstat
#    - socket
#  process.include_top_n:
#    by_cpu: 5      # include top 5 processes by CPU
#    by_memory: 5   # include top 5 processes by memory
#  cpu.metrics:  ["percentages","normalized_percentages"]  # Add cpu metrics normalized by number of cores
- module: system
  period: 5m
  metricsets:
    - filesystem
#    - fsstat
  processors:
  - drop_event.when.regexp:
      system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
# We always want to have metrics about SSR processes
#- module: system
#  period: 5s
#  metricsets:
#    - process
#  processes: ['.*node.*']
#- module: system
#  period: 15m
#  metricsets:
#    - uptime
