---
# tasks file for opsagent
- name: "Ops Agent Repo Script Download"
  get_url:
    url: "https://dl.google.com/cloudagents/add-google-cloud-ops-agent-repo.sh"
    dest: .
- name: "Install OpsAgent"
  shell: "bash add-google-cloud-ops-agent-repo.sh --also-install"
