---
- name: "Pin PHP version to prevent from update bug"
  template:
    src: php.pref.j2
    dest: /etc/apt/preferences.d/php.pref

- name: "Update System (Debian)"
  apt: update_cache=yes cache_valid_time=86400 upgrade=dist autoremove=yes
  when: not is_docker|bool
  retries: 3
  delay: 5

- name: Install unattended-upgrades
  apt: pkg=unattended-upgrades state=present
  when: not is_docker|bool
  retries: 3
  delay: 5

- name: Enforce language
  lineinfile: >
    dest=/etc/environment
    line="{{ item }}"
    state=present
  with_items:
    - "LANG=en_US.UTF-8"
    - "LC_ALL=en_US.UTF-8"

- name: "Check if reboot is required"
  stat: path=/var/run/reboot-required
  register: reboot_required
