---
- name: Check if project already exists
  stat:
    path: "{{ root }}"
  register: catwalk

- block:
  - name: Create mock catwalk directory
    file:
      path: "{{ root }}/public"
      state: directory
      recurse: "yes"
      owner: "{{ web_user }}"
      group: "{{ web_user }}"

  - name: Create mock build.xml
    copy:
      src: build.xml
      dest: "{{ root }}/build.xml"
      owner: "{{ web_user }}"
      group: "{{ web_user }}"

  - name: Create mock index.php
    copy:
      src: index.php
      dest: "{{ root }}/public/index.php"
      owner: "{{ web_user }}"
      group: "{{ web_user }}"

  when: not catwalk.stat.exists
