---
- name: Ensure MySQL databases are present.
  mysql_db:
    login_user: "{{mysql_root_username }}"
    login_password: "{{mysql_root_password }}"
    login_host: "{{ cloud_mysql_host | default('localhost') }}"
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8mb4_unicode_ci') }}"
    encoding: "{{ item.encoding | default('utf8mb4') }}"
    state: present
  with_items: '{{ mysql_databases }}'
  tags: ['new-project']

- name: Ensure MySQL users are present.
  mysql_user:
    login_user: "{{mysql_root_username }}"
    login_password: "{{mysql_root_password }}"
    login_host: "{{ cloud_mysql_host | default('localhost') }}"
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    state: present
  with_items: '{{ mysql_users }}'
  tags: ['new-project']
