import React, { ChangeEvent, useState } from 'react';
import { useRouter } from 'next/router';
import { LoadingIcon } from 'components/commercetools-ui/icons/loading';
import { useFormat } from 'helpers/hooks/useFormat';
import { useCart } from 'frontastic';

const PoNumber: React.FC = () => {
  const { formatMessage } = useFormat({ name: 'checkout' });
  const { orderCart } = useCart();
  const router = useRouter();
  const [data, setData] = useState({
    poNumber: '',
    invoiceMemo: '',
    comment: '',
  });

  const [isLoading, setIsLoading] = useState(false);

  const handleChange = (e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setData({
      ...data,
      [e.target.name]: e.target.value,
    });
  };

  const handleOrder = async () => {
    setIsLoading(true);
    await orderCart();
    setIsLoading(false);
    router.replace(
      {
        pathname: '/thank-you',
      },
      undefined,
      {
        shallow: false,
      },
    );
  };

  return (
    <form>
      <div className="mt-4">
        <p className="text-sm text-gray-500">
          {formatMessage({
            id: 'po-number-description',
            defaultMessage: 'Please enter a single authorized purchase order number generated by your organization.',
          })}
        </p>
        <p className="text-sm text-gray-500">
          {formatMessage({
            id: 'po-number-description-2',
            defaultMessage: 'The PO number and payment instructions will appear on the invoice.',
          })}
        </p>
        <label className="text-sm leading-tight text-neutral-700" htmlFor="billing-country">
          <span>{formatMessage({ id: 'po-number', defaultMessage: 'PO Number' })}</span> *
          <input
            className="input input-primary"
            id="po-number"
            name="poNumber"
            type="text"
            onChange={handleChange}
            value={data.poNumber}
            required
          />
        </label>
      </div>
      <div>
        <label className="text-sm leading-tight text-neutral-700" htmlFor="billing-country">
          <span>{formatMessage({ id: 'po-number-invoice', defaultMessage: 'Invoice Memo (optional)' })}</span>
          <input
            className="input input-primary"
            id="invoice-memo"
            name="invoiceMemo"
            type="text"
            onChange={handleChange}
            value={data.invoiceMemo}
          />
        </label>
      </div>
      <button className="button button-primary--small mr-4 mt-4 flex flex-row" type="button" onClick={handleOrder}>
        {formatMessage({ id: 'place-order', defaultMessage: 'Place order' })}
        {isLoading && <LoadingIcon className="h-6 w-6 animate-spin" />}
      </button>
    </form>
  );
};

export default PoNumber;
